name: Backend Workflow

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        type: string
        default: "17.0.1"
      DOCKER_REGISTRY:
        type: string
        default: "https://dbd.jfrog.io/artifactory/dbd-docker/"
    secrets:
      DBD_ARTIFACTORY_USER:
        required: true
      DBD_ARTIFACTORY_PASSWORD:
        required: true
      SONAR_TOKEN:
        required: true
jobs:

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: test --parallel and sonarqube
        env:
          DBD_ARTIFACTORY_USER: ${{ secrets.DBD_ARTIFACTORY_USER }}
          DBD_ARTIFACTORY_PASSWORD: ${{ secrets.DBD_ARTIFACTORY_PASSWORD }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew test sonarqube
      - name: Login to Docker Registry
        if: contains(github.ref,'main')
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.DOCKER_REGISTRY }}
          username: ${{ secrets.DBD_ARTIFACTORY_USER }}
          password: ${{ secrets.DBD_ARTIFACTORY_PASSWORD }}
      - name: Build & Publish to Artifactory
        if: contains(github.ref,'main')
        env:
          DBD_ARTIFACTORY_USER: ${{ secrets.DBD_ARTIFACTORY_USER }}
          DBD_ARTIFACTORY_PASSWORD: ${{ secrets.DBD_ARTIFACTORY_PASSWORD }}
        run: ./gradlew dockerTagsPush
