name: Backend Workflow

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        type: string
        default: "17.0.1"
    secrets:
      DBD_ARTIFACTORY_USER:
        required: true
      DBD_ARTIFACTORY_PASSWORD:
        required: true       
      SONAR_TOKEN:
        required: true
jobs:

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
      - name: Change wrapper permissions
        run: chmod +x ./gradlew   
      - name: test and sonarqube        
        env:          
          DBD_ARTIFACTORY_USER: ${{ secrets.DBD_ARTIFACTORY_USER }}
          DBD_ARTIFACTORY_PASSWORD: ${{ secrets.DBD_ARTIFACTORY_PASSWORD }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
        run: ./gradlew test sonarqube

  build:
    name: build
    runs-on: ubuntu-latest
    needs: [ "test"]

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
      - name: Change wrapper permissions
        run: chmod +x ./gradlew   
      - name: build
        env:          
          DBD_ARTIFACTORY_USER: ${{ secrets.DBD_ARTIFACTORY_USER }}
          DBD_ARTIFACTORY_PASSWORD: ${{ secrets.DBD_ARTIFACTORY_PASSWORD }}  
        run: ./gradlew docker

  publish-artifacts:
    name: Publish Artifacts
    runs-on: ubuntu-latest
    needs: [ "build"]

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
      - name: Change wrapper permissions
        run: chmod +x ./gradlew          
      - name: publish 
        env:          
          DBD_ARTIFACTORY_USER: ${{ secrets.DBD_ARTIFACTORY_USER }}
          DBD_ARTIFACTORY_PASSWORD: ${{ secrets.DBD_ARTIFACTORY_PASSWORD }}  
        run: ./gradlew artifactoryPublish    
                
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [ "publish-artifacts"]

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
      - name: Change wrapper permissions
        run: chmod +x ./gradlew          
      - name: deploy 
        env:          
          DBD_ARTIFACTORY_USER: ${{ secrets.DBD_ARTIFACTORY_USER }}
          DBD_ARTIFACTORY_PASSWORD: ${{ secrets.DBD_ARTIFACTORY_PASSWORD }}  
        run: echo "Here your should be your deployment script"            