name: Common Dependencies Workflow

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        type: string
        default: "17.0.1"
    secrets:
      DBD_ARTIFACTORY_USER:
        required: true
      DBD_ARTIFACTORY_PASSWORD:
        required: true        
jobs:
  publish-artifacts:
    name: Publish Artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
        env:          
          DBD_ARTIFACTORY_USER: ${{ secrets.DBD_ARTIFACTORY_USER }}
          DBD_ARTIFACTORY_PASSWORD: ${{ secrets.DBD_ARTIFACTORY_PASSWORD }}  
      - name: Change wrapper permissions
        run: chmod +x ./gradlew          
      - name: publish 
        run: ./gradlew publish          