name: Common Dependencies Workflow

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        type: string
        default: "17.0.1"
    secrets:
      DBD_ARTIFACTORY_USER:
        required: true
      DBD_ARTIFACTORY_PASSWORD:
        required: true        
jobs:
  pr-check:
    name: 'PR Title Checker'
    runs-on: ubuntu-latest         

    steps:
      - uses: deepakputhraya/action-pr-title@master@v1.0.2
        with:
          regex: '^\[((DBD)\-[0-9]+|[HOTFIX\-[0-9]+[0-9\.]*[0-9]+)\].*' # Regex the title should match.
      - uses: deepakputhraya/action-branch-name@master@v1.0.2
        if: github.base_ref == 'develop'
        with:
          regex: '^(feature\/(DBD)\-[0-9]+[\-_]|(hotfix|release)\/[0-9]+[0-9\.]*[0-9]+|main).*' # Regex the branch name should match.

  publish-artifacts:
    name: Publish Artifacts
    runs-on: ubuntu-latest
    needs: [ "pr-check"]

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
      - name: Change wrapper permissions
        run: chmod +x ./gradlew          
      - name: publish 
        env:          
          DBD_ARTIFACTORY_USER: ${{ secrets.DBD_ARTIFACTORY_USER }}
          DBD_ARTIFACTORY_PASSWORD: ${{ secrets.DBD_ARTIFACTORY_PASSWORD }}  
        run: ./gradlew publish          
        