name: Frontend Workflow

on:
  workflow_call:
    inputs:
      SERVICE_NAME:
        type: string
      SERVICE_VERSION:
        type: string
    secrets:
      DBD_ARTIFACTORY_DOCKER_USER:
        required: true
      DBD_ARTIFACTORY_DOCKER_PASSWORD:
        required: true
      DBD_ARTIFACTORY_DOCKER_ADDRESS:
        required: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: xom9ikk/split@v1
        id: service
        with:
          string: ${{ inputs.SERVICE_NAME }}
          separator: /
          limit: -1
      - name: Build and push artifact
        env:
          IMAGE_NAME: ${{ steps.service.outputs._1 }}
          IMAGE_TAG: ${{ inputs.SERVICE_VERSION }}      
          DBD_ARTIFACTORY_DOCKER_USER: ${{ secrets.DBD_ARTIFACTORY_DOCKER_USER }}
          DBD_ARTIFACTORY_DOCKER_PASSWORD: ${{ secrets.DBD_ARTIFACTORY_DOCKER_PASSWORD }}
          DBD_ARTIFACTORY_DOCKER_ADDRESS: ${{ secrets.DBD_ARTIFACTORY_DOCKER_ADDRESS }}
        run: |
          docker login ${{ secrets.DBD_ARTIFACTORY_DOCKER_ADDRESS }} -u ${{ secrets.DBD_ARTIFACTORY_DOCKER_USER }} -p ${{ secrets.DBD_ARTIFACTORY_DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DBD_ARTIFACTORY_DOCKER_ADDRESS }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          docker push ${{ secrets.DBD_ARTIFACTORY_DOCKER_ADDRESS }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
