name: Frontend Workflow

on:
  workflow_call:
    inputs:
      SERVICE_NAME:
        type: string
      SERVICE_VERSION:
        type: string
    secrets:
      DBD_ARTIFACTORY_USER:
        required: true
      DBD_ARTIFACTORY_PASSWORD:
        required: true
      DBD_ARTIFACTORY_ADDRESS:
        required: true
      SONAR_TOKEN:
        required: true
jobs:

  # test:
  #   name: test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: test and sonarqube        
  #       env:          
  #         DBD_ARTIFACTORY_USER: ${{ secrets.DBD_ARTIFACTORY_USER }}
  #         DBD_ARTIFACTORY_PASSWORD: ${{ secrets.DBD_ARTIFACTORY_PASSWORD }}  
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
  #       run: 

  build:
    name: build
    runs-on: ubuntu-latest
    # needs: [ "test"]

    steps:
      - uses: actions/checkout@v1
      - name: build
        env:          
          DBD_ARTIFACTORY_USER: ${{ secrets.DBD_ARTIFACTORY_USER }}
          DBD_ARTIFACTORY_PASSWORD: ${{ secrets.DBD_ARTIFACTORY_PASSWORD }}
          DBD_ARTIFACTORY_ADDRESS: ${{ secrets.DBD_ARTIFACTORY_ADDRESS }}
          SERVICE_NAME: ${{ inputs.SERVICE_NAME }}
          SERVICE_VERSION: ${{ inputs.SERVICE_VERSION }}
        run: echo SERVICE_NAME ${SERVICE_NAME} ; SERVICE_VERSION ${SERVICE_VERSION}
        # run: echo docker build -t ${{ DBD_ARTIFACTORY_ADDRESS }}/${{ SERVICE_NAME }}:${{ SERVICE_VERSION }} .

  publish-artifacts:
    name: Publish Artifacts
    runs-on: ubuntu-latest
    needs: [ "build"]

    steps:
      - name: publish 
        env:          
          DBD_ARTIFACTORY_USER: ${{ secrets.DBD_ARTIFACTORY_USER }}
          DBD_ARTIFACTORY_PASSWORD: ${{ secrets.DBD_ARTIFACTORY_PASSWORD }}
          DBD_ARTIFACTORY_ADDRESS: ${{ secrets.DBD_ARTIFACTORY_ADDRESS }}
          SERVICE_NAME: ${{ inputs.SERVICE_NAME }}
          SERVICE_VERSION: ${{ inputs.SERVICE_VERSION }}
        run: echo docker push ${DBD_ARTIFACTORY_ADDRESS}/${SERVICE_NAME}:${SERVICE_VERSION}    
