name: Frontend Workflow

on:
  workflow_call:
    inputs:
      SERVICE_NAME:
        type: string
      SERVICE_VERSION:
        type: string
    secrets:
      DBD_ARTIFACTORY_USER:
        required: true
      DBD_ARTIFACTORY_PASSWORD:
        required: true
      DBD_ARTIFACTORY_ADDRESS:
        required: true
      SONAR_TOKEN:
        required: true
jobs:

  # test:
  #   name: test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: test and sonarqube        
  #       env:          
  #         DBD_ARTIFACTORY_USER: ${{ secrets.DBD_ARTIFACTORY_USER }}
  #         DBD_ARTIFACTORY_PASSWORD: ${{ secrets.DBD_ARTIFACTORY_PASSWORD }}  
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
  #       run: 

  build:
    name: build
    runs-on: ubuntu-latest
    # needs: [ "test"]

    steps:
      - uses: actions/checkout@v1
      - uses: ASzc/change-string-case-action@v2
        id: tag
        with:
          string: ${{ inputs.SERVICE_VERSION }}
      - name: build
        env:
          IMAGE_TAG: ${{ steps.tag.outputs.lowercase }}      
        #   DBD_ARTIFACTORY_USER: ${{ secrets.DBD_ARTIFACTORY_USER }}
        #   DBD_ARTIFACTORY_PASSWORD: ${{ secrets.DBD_ARTIFACTORY_PASSWORD }}
        #   DBD_ARTIFACTORY_ADDRESS: ${{ secrets.DBD_ARTIFACTORY_ADDRESS }}
        #   SERVICE_NAME: ${{ inputs.SERVICE_NAME }}
        #   SERVICE_VERSION: ${{ inputs.SERVICE_VERSION }}
        run: echo SERVICE_NAME ${{ inputs.SERVICE_NAME }} SERVICE_VERSION ${{ inputs.SERVICE_VERSION }} IMAGE_TAG ${IMAGE_TAG}
        # run: |
        #   docker login -u ${{ secrets.DBD_ARTIFACTORY_ADDRESS }} -u ${{ secrets.DBD_ARTIFACTORY_USER }} -p ${{ secrets.DBD_ARTIFACTORY_PASSWORD }}

  # publish-artifacts:
  #   name: Publish Artifacts
  #   runs-on: ubuntu-latest
  #   needs: [ "build"]

  #   steps:
  #     - name: publish 
  #       env:          
  #         DBD_ARTIFACTORY_USER: ${{ secrets.DBD_ARTIFACTORY_USER }}
  #         DBD_ARTIFACTORY_PASSWORD: ${{ secrets.DBD_ARTIFACTORY_PASSWORD }}
  #         DBD_ARTIFACTORY_ADDRESS: ${{ secrets.DBD_ARTIFACTORY_ADDRESS }}
  #         SERVICE_NAME: ${{ inputs.SERVICE_NAME }}
  #         SERVICE_VERSION: ${{ inputs.SERVICE_VERSION }}
  #       run: echo docker push ${DBD_ARTIFACTORY_ADDRESS}/${SERVICE_NAME}:${SERVICE_VERSION}    
